before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    main: ./cmd/cli/main.go
    id: "mim"
    binary: mim
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - 386
      - arm
      - arm64
archives:
  - replacements:
      darwin: macOs
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
