name: Add binaries to Github release

on:
  push:
    tags:
      - "*" # triggers only if push new tag version, like `0.8.4` or else

jobs:
  goreleaser:
    name: GoReleaser build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0 # See: https://goreleaser.com/ci/actions/

      - name: Set up Go 1.19
        uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.19
        id: go

      - name: Check out source code
        uses: actions/checkout@v2.3.4

      - name: Write version file
        id: version_file
        run: |
          versionTag=$(echo $GITHUB_REF | cut -d / -f 3)
          echo "$versionTag" > "internal/command/VERSION"

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5.0.0
        with:
          version: latest
          args: release --clean

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
