name: Add binaries to Github release

on:
  push:
    tags:
      - "*" # triggers only if push new tag version, like `0.8.4` or else

jobs:
  goreleaser:
    name: GoReleaser build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0 # See: https://goreleaser.com/ci/actions/

      - name: Set up Go
        uses: actions/setup-go@v5.0.0
        with:
          go-version: 1.22.2
        id: go

      - name: Write version file
        id: version_file
        run: |
          versionTag=$(echo $GITHUB_REF | cut -d / -f 3)
          echo "$versionTag" > "internal/command/VERSION"

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5.0.0
        with:
          version: 1.25.1
          args: release --clean

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
